[project]
name = "Terminus"
authors = [
  { name="matee28", email="102618601+matee28@users.noreply.github.com" },
]

description = "Simulátor železničního magnáta"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "GPL-3.0-only"
license-files = [
    "LICENSE",
]

dynamic = ["dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {file = "VERSION"}


[project.scripts]
terminus-test = "terminus_test:main"


[project.urls]
Homepage = "https://github.com/matee28/Terminus"
Issues = "https://github.com/matee28/Terminus/issues"


[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]